
const products = [
 { id:"potato", name:"Potato 1kg", price:40, image:"images/potato.png" },
 { id:"onion", name:"Onion 1kg", price:40, image:"images/onion.png" },
 { id:"tomato", name:"Tomato 500gm", price:30, image:"images/tomato.png" },
 { id:"carrot", name:"Carrot 300gm", price:50, image:"images/carrot.png" },
 { id:"cabbage", name:"Cabbage 1pc", price:40, image:"images/cabbage.png" },
 { id:"cauliflower", name:"Cauliflower 1pc", price:50, image:"images/cauliflower.png" },
 { id:"capsicum", name:"Capsicum 300gm", price:60, image:"images/capsicum.png" },
 { id:"ladyfinger", name:"Lady Finger 300gm", price:50, image:"images/lady-finger.png" },
 { id:"frenchbeans", name:"French Beans 300gm", price:60, image:"images/french-beans.png" },
 { id:"clusterbeans", name:"Cluster Beans 300gm", price:60, image:"images/cluster-beans.png" },
 { id:"greenpeas", name:"Green Peas 300gm", price:60, image:"images/green-peas.png" },
 { id:"drumstick", name:"Drumstick 300gm", price:60, image:"images/cleaned-chopped-drumstick.png" },
 { id:"bittergourd", name:"Bitter Gourd 300gm", price:50, image:"images/bitter-gourd.png" },
 { id:"ridgegourd", name:"Ridge Gourd 300gm", price:50, image:"images/ridge-gourd.png" },
 { id:"spongegourd", name:"Sponge Gourd 300gm", price:50, image:"images/sponge-gourd.png" },
 { id:"pumpkin", name:"Pumpkin 500gm", price:40, image:"images/red-pumpkin.png" },
 { id:"palak", name:"Palak 300gm", price:30, image:"images/palak.png" },
 { id:"methi", name:"Methi 300gm", price:30, image:"images/methi.png" },
 { id:"coriander", name:"Coriander", price:20, image:"images/coriander.png" },
 { id:"pudina", name:"Pudina", price:20, image:"images/pudina.png" },
 { id:"greenchilli", name:"Green Chilli", price:20, image:"images/green-chilli.png" },
 { id:"garlic", name:"Garlic 250gm", price:60, image:"images/peeled-garlic.png" },
 { id:"lemon", name:"Lemon (3 pcs)", price:20, image:"images/lemon.png" },
 { id:"coconut", name:"Coconut", price:40, image:"images/fresh-coconut.png" },
 { id:"pulavmix", name:"Pulav Mix", price:40, image:"images/mixed-pulav-vegetables.png" }
];
